DA-363: Export Query results as SQL++ inserts/upserts
couchbaselabs/couchbase_jetbrains_plugin pull request #101
Opened 2023-09-27 09:10 UTC by teetangh

2023-10-17 19:41 UTC, deniswsrosa requested changes
- revert the gradle.xml file
-  add a divider above the "SQL++ UPSERT" option
- Could you please open a popup asking the user for the collection name instead of just adding "my_collection"? The phrase could be something like "Inform the name of the collection that should be used in the dataset" . This way the user doesn't need to open the dataset and replaced "my_collection" with that he/she wants.

Everything else looks fine for me.

2023-10-19 04:10 UTC, teetangh commented on .idea/gradle.xml
Have reverted the file. Already in gitignore as .idea/gradle.xml

2023-10-19 19:07 UTC, deniswsrosa commented
@teetangh 2 small fixes:

- You need to validate that the user has specified a name for the collection
- You need to check if there are any invalid characters in the collection's name. Note that the name could be fully qualified (`travel-sample`.inventory.some_collection)

2023-10-19 19:07 UTC, deniswsrosa requested changes
Check my comment in the PR. The collection name needs to be validated.

2023-11-19 14:43 UTC, deniswsrosa approved these changes

2023-11-19 14:43 UTC, merged