Complete Rewrite of the schema Tree
couchbaselabs/couchbase_jetbrains_plugin pull request #3
Opened 2023-05-26 11:06 UTC by teetangh

2023-05-26 12:51 UTC, deniswsrosa requested changes
extractTypes needs to be rewritten

2023-05-26 12:51 UTC, deniswsrosa commented on src/main/java/com/couchbase/intellij/database/DataLoader.java
> +                    // ActiveCluster.getInstance().get().bucket(bucketName)
remove unused code

2023-05-26 12:51 UTC, deniswsrosa commented on src/main/java/com/couchbase/intellij/database/DataLoader.java
> +                    // // Approach 1: Using HTTP Request
remove chatgpt comments

2023-05-26 12:51 UTC, deniswsrosa commented on src/main/java/com/couchbase/intellij/database/DataLoader.java
> +                    // treeModel.nodeStructureChanged(parentNode);
remove commented code

2023-05-26 12:51 UTC, deniswsrosa commented on src/main/java/com/couchbase/intellij/database/DataLoader.java
> +                                    result.put(key, "array of " + extractTypes(items.getObject("properties")));
this code looks buggy to me. Needs to be completely rewritten.

2023-05-26 18:23 UTC, teetangh commented on src/main/java/com/couchbase/intellij/database/DataLoader.java
> +                    // ActiveCluster.getInstance().get().bucket(bucketName)
removed

2023-05-26 18:23 UTC, teetangh commented on src/main/java/com/couchbase/intellij/database/DataLoader.java
> +                    // // Approach 1: Using HTTP Request
removed

2023-05-26 18:23 UTC, teetangh commented on src/main/java/com/couchbase/intellij/database/DataLoader.java
> +                    // treeModel.nodeStructureChanged(parentNode);
removed

2023-05-27 08:08 UTC, deniswsrosa approved these changes

2023-05-27 17:20 UTC, merged